# The optimizationBenchmarking.org tool suite is a Java Project
language: java

# By default, it runs under Java 7
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
    
# Cache Maven dependencies to speed up builds.
cache:
  directories:
  - $HOME/.m2
  
  
# install texlive: we can use this to test LaTeX document generation
install:
  - sudo apt-get -q -y -f update
  - sudo apt-get -q -y -f install texlive
  - sudo apt-get -q -y -f install r-base r-base-dev
  
# custom build step
script: mvn -C -B test compile

# fix for buffer overflows in getLocalHostName
# https://github.com/travis-ci/travis-ci/issues/5227
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*